### ISSUE TITLE
Are there any plans for subsequent public disclosure of the metrics marked with an asterisk (*) in the Huawei Public dataset?

### ISSUE THREAD

**Issue by chatiti** [sir-lab/data-release#2]
![image](https://github.com/sir-lab/data-release/assets/79210532/94d57b6a-8b21-46ca-b45a-93653ca440f6)
Metrics such as cold start cost or package sizes. : )

**Comment by ajoosen** [comment]
> ![image](https://github.com/sir-lab/data-release/assets/79210532/94d57b6a-8b21-46ca-b45a-93653ca440f6)
> Metrics such as cold start cost or package sizes. : )

Now we have a new detailed dataset of cold starts and a paper about cold starts in multiple regions. See [here](https://github.com/sir-lab/data-release/blob/main/README_data_release_2025.md).
